### ISSUE TITLE
Error Creating Branch

### ISSUE THREAD

**Issue by gbargsley** [devops-collective-inc/why-powershell#1]
I forked the repo, cloned the repo locally.  When I try and make a branch and publish it I get the following error.  I am not the best at Git, but that is usually my steps.

![image](https://user-images.githubusercontent.com/169602/42606850-55662a56-8545-11e8-9bb7-8f30889882f3.png)

**Comment by concentrateddon** [comment]
Try logging out and back in. It’s an issue with the client - if that doesn’t work you’re past my level of expertise :). You’re not even accessing our repo, so there’s not even anything I can check on my end.

On Jul 11, 2018, at 19:02, Garry Bargsley <notifications@github.com<mailto:notifications@github.com>> wrote:


I forked the repo, cloned the repo locally. When I try and make a branch and publish it I get the following error. I am not the best at Git, but that is usually my steps.

[image]<https://user-images.githubusercontent.com/169602/42606850-55662a56-8545-11e8-9bb7-8f30889882f3.png>

**Comment by gbargsley** [comment]
I closed the client and tried to start over same result.  Wonder if it has to do with creating a branch off of master.

**Comment by gbargsley** [comment]
Working with a Git export friend of mine, he helped me figure out I don't have access to the repo to create a branch and push to the repo.

**Comment by concentrateddon** [comment]
Anyone has permission to fork the repo and mess with their own fork. Or should. That’s the point of open source.

On Jul 11, 2018, at 19:59, Garry Bargsley <notifications@github.com<mailto:notifications@github.com>> wrote:


Working with a Git export friend of mine, he helped me figure out I don't have access to the repo to create a branch and push to the repo.

**Comment by concentrateddon** [comment]
So, let's be clear - you're meant to clone the repo, usually into a local repo or a GitHub-based one. You then mess with your own repo, and submit a pull request back to Master. That's a little different form creating a new branch within the same repo.

**Comment by concentrateddon** [comment]
Posted a tutorial with pics :) I imagine it'll help others, at least. See https://github.com/devops-collective-inc/how-to-contribute/blob/master/general_instructions.md.

**Comment by gbargsley** [comment]
Ok, that is a little different flow that I am used to.  I will do it that way.  Thanks.

**Comment by gbargsley** [comment]
Yeah, reading your instructions.  That is what I am doing.  The Push to Origin is the failure point.  That is where I get permissions denied.

**Comment by concentrateddon** [comment]
So, that would be an error pushing **into your own account** - I can't assist with that. It's push into your account, and _then_ create a PR back into the organization's repo. I don't have any control until that PR request happens.

**Comment by gbargsley** [comment]
I see what it is.  I was not clone from my account, I was cloning from the devops account.  Thanks for the walk through.
